version: '3'

    services:
      proxy:
        image: traefik:latest
        command: --web --docker --docker.domain=YOURDOMAIN.local --logLevel=DEBUG
        networks:
          - traefik
        ports:
          - 80:80
          - 443:443
          - 8080:8080
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /root/traefik.toml:/traefik.toml
          - /root/acme.json:/acme.json

      ghost:
        image: ghost:latest
        labels:
          - "traefik.frontend.rule=Host:blog.YOURDOMAIN"
        networks:
          - traefik
      nginx:
        image: nginx:latest
        labels:
          - "traefik.frontend.rule=Host:site.YOURDOMAIN"
        networks:
          - traefik

    networks:
      traefik:
        external: true
